### ISSUE TITLE
Hide answers, questions, comments style.

### ISSUE THREAD

**Issue by yerbol89** [q2a/question2answer#168]
``` css
.qa-a-list-item-hidden .qa-voting {
    color: #ccc;
}
.qa-a-list-item-hidden .qa-a-item-content {
    color: #999;
}
.qa-a-list-item-hidden .qa-a-item-what {
    color: #ccc;
}
.qa-a-list-item-hidden .qa-a-item-meta {
    color: #ccc;
}
.qa-a-list-item-hidden .qa-a-item-who-title {
    color: #999;
}
.qa-a-list-item-hidden .qa-user-link {
    color: #999;
}
.qa-c-item-hidden .qa-c-item-content {
    color: #bbb;
}
.qa-c-item-hidden .qa-c-item-link {
    color: #aaf;
}
.qa-c-item-hidden .qa-c-item-what {
    color: #ccc;
}
.qa-c-item-hidden .qa-c-item-meta {
    color: #ccc;
}
.qa-c-item-hidden .qa-c-item-who-title {
    color: #999;
}
.qa-c-item-hidden .qa-user-link {
    color: #999;
}
.qa-q-view-hidden .qa-voting {
    color: #ccc;
}
.qa-q-view-hidden .qa-q-view-content {
    color: #999;
}
.qa-q-view-hidden .qa-q-view-meta {
    color: #ccc;
}
.qa-q-view-hidden .qa-user-link {
    color: #999;
}
.qa-q-view-hidden .qa-q-view-who-title {
    color: #999;
}
.qa-q-view-hidden .qa-category-link {
    color: #999;
}
.qa-q-view-hidden .qa-tag-link {
    color: #ccc;
    opacity: 0.5px;
}
```

![default](https://cloud.githubusercontent.com/assets/993795/5353701/6e74bf8c-7fa7-11e4-90be-f3653b9e5a30.png)
