### ISSUE TITLE
Removing overflow: hidden from some content wrapper

### ISSUE THREAD

**Issue by q2amarket** [q2a/question2answer#347]
@svivian 

I have just downloaded ***1.7.2*** and was checking with my on going development and found one minor but annoying issue. in ***SnowFlat***

`qa-body-wrapper`, `qa-main`, and `qa-main-wrapper` has `overflow: hidden;` property. This is an issue when we use any jquery dropdown plugin. It is hiding drop-down list. (see image)

![hidden](https://cloud.githubusercontent.com/assets/2882691/12175113/e170417e-b579-11e5-9694-73fd7826186d.PNG)

#### qa-styles.css @ line #882
```css
.qa-main, .qa-main-wrapper {
    overflow: hidden;
}
```

#### qa-styles.css @ line #887
```css
.qa-body-wrapper {
    margin: 10px auto;
    overflow: hidden;
    padding: 0 10px;
}
```

## Solution
***Using `.clearfix` for those wrappers could resolves the issue***

This is just by chance if you are working on it otherwise, I will try to send you the pull requests on it next week if possible.
